version: '2.4'

services:

  simple-nodejs:
    image: mohclips/simple-nodejs:latest
    tty: true
    container_name: simple-nodejs
    restart: unless-stopped

    ports:
      - 3001:3000

    #volumes:
    #  - ./shared/:/tmp/shared/

    healthcheck:
      test:  wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
